from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

HOST = "127.0.0.1"
PORT = 8000
WEBSOCKET_PATH = "/ws/telemetry"

BUFFER_MAX_SIZE = 10000
BATCH_SIZE = 250
FLUSH_INTERVAL_SEC = 0.5

BRUTE_FORCE_WINDOW_SEC = 10
BRUTE_FORCE_THRESHOLD = 5

PORT_SCAN_WINDOW_SEC = 15
PORT_SCAN_UNIQUE_PORTS_THRESHOLD = 10

DATA_EXFIL_WINDOW_SEC = 30
DATA_EXFIL_BYTES_THRESHOLD = 5_000_000  # 5 MB

SEVERITY_SCORES = {
    "INFO": 1,
    "LOW": 3,
    "MEDIUM": 5,
    "HIGH": 8,
    "CRITICAL": 10,
}